const express=require('express'),multer=require('multer'),crypto=require('crypto'),path=require('path'),postgres=require('postgres');
const {createClient}=require('@supabase/supabase-js');
const app=express(),COOKIE='beotnaru_session',BUCKET='beotnaru-photos';
const initial={site:{tel:'02-0000-0000',email:'',orgName:'벗나루 청춘태권도',address:'서울 성동구 ○○로 00',hours:'평일 09:00–18:00'},sites:[{name:'공릉복지관',area:'노원구',start:'2025년 3월',ym:'2025-03',state:'진행 중'},{name:'금호복지관',area:'성동구',start:'2025년 4월',ym:'2025-04',state:'진행 중'},{name:'약수복지관',area:'중구',start:'2025년 9월',ym:'2025-09',state:'진행 중'},{name:'금빛호수 옥수관',area:'성동구',start:'2025년 9월',ym:'2025-09',state:'자체 운영'},{name:'옥수복지관',area:'성동구',start:'2026년 2월',ym:'2026-02',state:'진행 중'}],news:[],photos:[1,2,3,4,5,6].map(n=>({file:`photos/p${n}.jpg`,caption:'〔촬영 시기, 장소〕',...(n===1?{big:true}:{})}))};
let sql,ready;
function db(){if(!process.env.POSTGRES_URL)throw Error('POSTGRES_URL 환경 변수가 없습니다.');return sql||(sql=postgres(process.env.POSTGRES_URL,{ssl:'require',max:1,prepare:false}))}
function hash(p,s=crypto.randomBytes(16).toString('hex')){return{salt:s,passwordHash:crypto.scryptSync(p,s,64).toString('hex')}}
async function init(){if(!ready)ready=(async()=>{const q=db();await q`create table if not exists beotnaru_settings (key text primary key,value jsonb not null)`;await q`create table if not exists beotnaru_admins (username text primary key,salt text not null,password_hash text not null,must_change boolean not null default true)`;await q`create table if not exists beotnaru_sessions (token text primary key,username text not null,expires_at timestamptz not null)`;await q`delete from beotnaru_sessions where expires_at<now()`;const a=await q`select username from beotnaru_admins where username='백승봉'`;if(!a.length){const h=hash('1234');await q`insert into beotnaru_admins values ('백승봉',${h.salt},${h.passwordHash},true)`}await q`insert into beotnaru_settings values ('content',${q.json(initial)}) on conflict (key) do nothing`})().catch(e=>{ready=null;throw e});return ready}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(v=>v.trim()).filter(Boolean).map(v=>{const i=v.indexOf('=');return[decodeURIComponent(v.slice(0,i)),decodeURIComponent(v.slice(i+1))]}))}
async function auth(req,res,next){try{await init();const token=cookies(req)[COOKIE];if(!token)return res.status(401).json({error:'로그인이 필요합니다.'});const r=await db()`select username from beotnaru_sessions where token=${token} and expires_at>now()`;if(!r.length)return res.status(401).json({error:'로그인이 필요합니다.'});req.user=r[0].username;next()}catch(e){next(e)}}
app.use(express.json({limit:'2mb'}));
app.get('/api/content',async(req,res,next)=>{try{await init();const r=await db()`select value from beotnaru_settings where key='content'`;res.json(r[0].value)}catch(e){next(e)}});
app.post('/api/login',async(req,res,next)=>{try{await init();const r=await db()`select * from beotnaru_admins where username=${String(req.body.username||'')}`;if(!r.length)return res.status(401).json({error:'아이디 또는 비밀번호가 올바르지 않습니다.'});const a=r[0],attempt=hash(String(req.body.password||''),a.salt).passwordHash;if(!crypto.timingSafeEqual(Buffer.from(attempt,'hex'),Buffer.from(a.password_hash,'hex')))return res.status(401).json({error:'아이디 또는 비밀번호가 올바르지 않습니다.'});const token=crypto.randomBytes(32).toString('hex');await db()`insert into beotnaru_sessions values (${token},${a.username},now()+interval '8 hours')`;res.cookie(COOKIE,token,{httpOnly:true,sameSite:'lax',secure:true,maxAge:28800000,path:'/'}).json({ok:true,mustChange:a.must_change})}catch(e){next(e)}});
app.get('/api/session',async(req,res,next)=>{try{await init();const token=cookies(req)[COOKIE];if(!token)return res.json({loggedIn:false});const r=await db()`select a.username,a.must_change from beotnaru_sessions s join beotnaru_admins a on a.username=s.username where s.token=${token} and s.expires_at>now()`;res.json(r.length?{loggedIn:true,username:r[0].username,mustChange:r[0].must_change}:{loggedIn:false})}catch(e){next(e)}});
app.post('/api/change-password',auth,async(req,res,next)=>{try{const p=String(req.body.password||'');if(p.length<6)return res.status(400).json({error:'새 비밀번호는 6자 이상이어야 합니다.'});const h=hash(p);await db()`update beotnaru_admins set salt=${h.salt},password_hash=${h.passwordHash},must_change=false where username=${req.user}`;res.json({ok:true})}catch(e){next(e)}});
app.put('/api/content',auth,async(req,res,next)=>{try{const a=await db()`select must_change from beotnaru_admins where username=${req.user}`;if(a[0].must_change)return res.status(403).json({error:'먼저 비밀번호를 변경하세요.'});if(!req.body||typeof req.body!=='object')return res.status(400).json({error:'저장할 내용이 올바르지 않습니다.'});await db()`insert into beotnaru_settings values ('content',${db().json(req.body)}) on conflict (key) do update set value=excluded.value`;res.json({ok:true})}catch(e){next(e)}});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10485760},fileFilter:(r,f,cb)=>cb(null,/^image\/(jpeg|png|webp|gif)$/.test(f.mimetype))});
app.post('/api/upload',auth,upload.single('photo'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({error:'JPG, PNG, WEBP 또는 GIF 이미지를 선택하세요.'});const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY;if(!url||!key)throw Error('Supabase Storage 환경 변수가 없습니다.');const sb=createClient(url,key,{auth:{persistSession:false}}),listed=await sb.storage.listBuckets();if(listed.error)throw listed.error;if(!listed.data.some(b=>b.name===BUCKET)){const c=await sb.storage.createBucket(BUCKET,{public:true,fileSizeLimit:10485760,allowedMimeTypes:['image/jpeg','image/png','image/webp','image/gif']});if(c.error)throw c.error}const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif'}[req.file.mimetype],name=`${Date.now()}-${crypto.randomBytes(8).toString('hex')}.${ext}`,saved=await sb.storage.from(BUCKET).upload(name,req.file.buffer,{contentType:req.file.mimetype});if(saved.error)throw saved.error;res.json({file:sb.storage.from(BUCKET).getPublicUrl(name).data.publicUrl})}catch(e){next(e)}});
app.post('/api/logout',async(req,res,next)=>{try{const token=cookies(req)[COOKIE];if(token){await init();await db()`delete from beotnaru_sessions where token=${token}`}res.clearCookie(COOKIE,{path:'/'}).json({ok:true})}catch(e){next(e)}});
app.use(express.static(__dirname,{index:'index.html',dotfiles:'deny'}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'서버 처리 중 오류가 발생했습니다.'})});
module.exports=app;

